ecomm_project/Cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove/<int:product_id>/', views.remove_cart, name="remove_cart"),
    path('item_delete/<int:product_id>/', views.item_delete, name="item_delete"),

]

ecomm_project/ecomm_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopApp.urls')),
    path('search/', include('searchApp.urls')),
    path('cart/', include('Cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecomm_project/searchApp/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),

]

ecomm_project/shopApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shopApp import views

app_name = 'shopApp'

urlpatterns = [
    path('', views.AllProductCat, name='allProductCat'),
    path('<slug:c_slug>/', views.AllProductCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:p_slug>', views.prod_detail, name='productDetail'),
]

ecomm_project/Cart/models.py
from django.db import models
from shopApp.models import Category, Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True, unique=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return str(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.prod_price * self.quantity

    def __str__(self):
        return str(self.product)

ecomm_project/searchApp/models.py
from django.db import models

# Create your models here.

ecomm_project/shopApp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    category_desc = models.TextField(blank=True)
    cat_image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering=('category_name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shopApp:product_by_category', args=[self.slug])


    def __str__(self):
        return '{}'.format(self.category_name)

class Product(models.Model):
    prod_name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    prod_desc = models.TextField(blank=True)
    prod_price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    prod_image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('prod_name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopApp:productDetail', args=[self.category.slug, self.slug])


    def __str__(self):
        return '{}'.format(self.prod_name)

ecomm_project/Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopApp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    print(Cart.cart_id , "-->this is key")
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        print(cart)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
    cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            cart=cart,
            quantity=1
        )
        cart_item.save()

    return redirect('cart:cart_detail')



def remove_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.prod_price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', {'cart_items': cart_items, 'total': total, 'counter': counter})

def item_delete(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomm_project/searchApp/views.py
from django.shortcuts import render
from shopApp.models import Product
from django.db.models import Q


# Create your views here.
def searchResult(request):
    print(request)
    products = None
    query = None
    if 'search' in request.GET:
        query = request.GET.get('search')
        products = Product.objects.all().filter(Q(prod_name__contains=query) | Q(prod_desc__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecomm_project/shopApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def index(request):
    return HttpResponse("Hello")

def AllProductCat(request, c_slug=None,):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, availability=True)
    else:
        products_list = Product.objects.all().filter(availability=True)

    # pagination
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)
    #     pagination ends

    return render(request, 'category.html', {'category':c_page, 'products':products})

def prod_detail(request, p_slug, c_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product':product})

ecomm_project/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <script src="https://kit.fontawesome.com/d3ddf9244a.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@1,200&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">

    {% include 'header.html' %}
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}

</div>

{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>



</body>
</html>

ecomm_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the Cart page. Please review your items and proceed with the order.
{% endblock %}

{% block title %}
        My Shopping Cart
{% endblock %}
{% block content %}

{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h2 class="text-center my-title">Your bag is empty! Let’s fill it up shall we?</h2>
            <h1></h1>
            <br>
            <div><a class="btn btn-empty-bag" href="{% url 'shopApp:allProductCat' %}">Continue Shopping</a> </div>
        </div>
    </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">
            My Shopping Cart <br>
        </h1>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class=" table custom-product-table">
                <thead class="custom-thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.prod_image.url}}" alt="{{cart_item.product.prod_name" class="my-prod-image my-image-padding float-left rounded custom_image "> </a>

                        </td>
                        <td style="text-align:left">
                            {{cart_item.product.prod_name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            Price: &#x20b9;{{cart_item.product.prod_price}}
                            <br>
                            Qty: {{cart_item.quantity}}
                        </td>
                        <td>
                            $ {{cart_item.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td style="width:15%">
                            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom-a">
                                <i class="fa fa-plus-square-o custom-icon"></i></a>
                            <a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="custom-a">
                                <i class="fa fa-minus custom-icon"></i></a>
                                <a href="{% url 'cart:item_delete' cart_item.product.id %}" class="custom-a"><i class="fa fa-trash custom-icon"></i></a>
                        </td>
                        {% else %}
                        <td>
                                <a disabled><i class="fa fa-plus-square-o custom-icon"></i></a>
                                <a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="custom-a">
                                <i class="fa fa-minus custom-icon"></i></a>
                                <a href="{% url 'cart:item_delete' cart_item.product.id %}" class="custom-a"><i class="fa fa-trash custom-icon"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table custom-product-table">
                <thead class="custom-thead">
                <tr>
                    <th colspan="5">
                        CheckOut
                    </th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                    <tr>
                        <td>
                            Please review your Shopping Cart Items before Checkout.
                        </td>
                    </tr>
                <tr>
                    <td class="text-left">You Pay({{counter}} Items):<strong>&#x20b9;{{total}}</strong></td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a class="btn btn-empty-bag" href="{% url 'shopApp:allProductCat' %}"><b>Continue Shopping</b></a>
            </div>
        </div>

    </div>

</div>
{% endif %}


{% endblock %}

ecomm_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category_desc|truncatewords:150 }}
    {% else %}
        Welcome to YourShop store. Shop All Day any Time.
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.category_name}} - YourShop
    {% else %}
       See our New Collections
    {% endif %}
{% endblock %}

{% block content %}

        <div>
            <div class="row my-row-class">
                <div class="mx-auto">
                    <p>
                        <a href="{% url 'shopApp:allProductCat' %}">Our Product Collection </a>
                        {% if category %}
                        <a>| {{category.category_name}}</a>
                        {% endif %}
                    </p>
                </div>

            </div>
        </div>


{% if category %}

<div class="mx-auto">
    <img class="my-image" src="{{category.cat_image.url}}" alt="{{category_name}}">
</div>
    </br>
<div>
    <h1 class="text-center my-title">{{category.category_name}}</h1>
    <p class="text-justify">{{category.category_desc}}</p>
</div>
<br/>
    {% else %}
<div>
    <img class="my-image my-image-padding" src="{% static 'img/banner.png' %}" alt="Our Products">
</div>
<br>
<div>
    <h1 class="text-center my-title">Welcome to Artisans Cake</h1>
    <p class="text-justify"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,
    </p>
</div>
{% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my-bottom-margin col-9 col-md-4 col-sm-12 col-lg-4">
            <div class="container">
                <div class="card text-center" style="min-width: 18rem;">
                   <a href="{{product.get_url}}"><img class="card-image-top my-prod-image" src="{{product.prod_image.url}}" alt="{{product.prod_name}}"></a>
                  <div class="card-body">
                    <h5 class="card-text">{{product.prod_name}}</h5>
                      <p class="card-text">&#x20b9;{{product.prod_price}}</p>
                  </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
           <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn-btn-light btn-sm {% if products.number == pg %}active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
             {% endif %}
        </div>
        <br>
    </div>
</div>


{% endblock %}

ecomm_project/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my-footer">
  <p class="text-center">&copy; Your Shop Pty Ltd. All rights reserved.</p>
</div>

ecomm_project/templates/header.html
{% load static %}
<header>
    <div>
        <center>
        <a href="{% url 'shopApp:allProductCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage" style="width:130px; height:75px;"></a>
        </center>

    </div>
</header>

ecomm_project/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopApp:allProductCat' %}">Shop</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.category_name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <div class="display-flex">
              <div>
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">Your Cart</a>
              </div>
              <div class="display-flex" style="margin-top:10px;">
                  <div>
                    <i class="fa-solid fa-cart-shopping"></i>
                  </div>
                  {% if counter > 0 %}
                  <div class="cart-count">
                    {{counter}}
                  </div>
                  {% endif %}
              </div>
          </div>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'search:searchResult' %}" method="GET">
        {% csrf_token %}
        <input type="search" name="search" class="form-control me-2" placeholder="Search here!">
        <button type="submit" class="btn btn-clear"><i class="fa-solid fa-magnifying-glass fa-xl" style="color:grey;"></i></button>
      </form>

    </div>
  </div>
</nav>

ecomm_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.prod_desc|truncatewords:150 }}

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.prod_name}}
    {% endif %}
{% endblock %}


{% block content %}
<div class="row my_prod_row">
    <div class="mx-auto">
        <p ><a href="{% url 'shopApp:allProductCat' %}">Home</a> |
        <a href="{{product.category.get_url}}" >{{product.category}}</a> | {{product.prod_name}}</p>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <div style="min-width:18rem;">
                <img class="my-prod-image" src="{{product.prod_image.url}}" alt="{{product.prod_name}}">
            </div>
        </div>
    </div>
    <div>
        <div class="container" style="margin-bottom:10px;">
            <div class="col-md-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="my_product_title">{{product.prod_name}}</h1>
                <p>${{product.prod_price}}</p>
                <p class="my_prod_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.prod_desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecomm_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        Welcome to Artisans Bakery! We specialize in creating cakes and pastries according to your design. Let us gild your celebration by baking the perfect cake. Welcome in!"

{% endblock %}

{% block title %}
        Searching...
{% endblock %}


{% block content %}
<div>
        <p class="text-center my-search-text">
                You have searched for :<b>"{{query}}"</b>
        </p>
</div>
<div class="container">
    <div class="row mx-auto">
            {% for product in products %}
            <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="container">
                    <div class="card text-center" style="min-width: 18rem;">
                       <a href="{{product.get_url}}"><img class="card-image-top my-prod-image" src="{{product.prod_image.url}}" alt="{{product.prod_name}}"></a>
                      <div class="card-body">
                        <h5 class="card-text">{{product.prod_name}}</h5>
                          <p class="card-text">&#x20b9;{{product.prod_price}}</p>
                      </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my-search-text">0 results found!!</p>
            </div>
        {% endfor %}
    </div>
</div>
  {% endblock %}